version: "3.3"
services:
  data:
    stdin_open: true
    tty: true
    container_name: kpu_bulletin_board_db
    image: kpu_bulletin_board_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "qwer1234"
    ports:
      - "127.0.0.1:53306:3306"
      - "127.0.0.1:33060:33060"
    expose:
      - "3306"
      - "33060"
